package com.jeckonly.designsystem.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006973)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF90F1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F23)
val md_theme_light_secondary = Color(0xFF4A6366)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE7EB)
val md_theme_light_onSecondaryContainer = Color(0xFF051F22)
val md_theme_light_tertiary = Color(0xFF515E7D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD9E2FF)
val md_theme_light_onTertiaryContainer = Color(0xFF0D1B36)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFD)
val md_theme_light_onBackground = Color(0xFF191C1D)
val md_theme_light_surface = Color(0xFFFAFDFD)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E6)
val md_theme_light_onSurfaceVariant = Color(0xFF3F484A)
val md_theme_light_outline = Color(0xFF6F797A)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
val md_theme_light_inverseSurface = Color(0xFF2D3131)
val md_theme_light_inversePrimary = Color(0xFF4ED8E9)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006973)
val md_theme_light_outlineVariant = Color(0xFFBEC8CA)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4ED8E9)
val md_theme_dark_onPrimary = Color(0xFF00363C)
val md_theme_dark_primaryContainer = Color(0xFF004F57)
val md_theme_dark_onPrimaryContainer = Color(0xFF90F1FF)
val md_theme_dark_secondary = Color(0xFFB1CBCF)
val md_theme_dark_onSecondary = Color(0xFF1C3438)
val md_theme_dark_secondaryContainer = Color(0xFF324B4E)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE7EB)
val md_theme_dark_tertiary = Color(0xFFB9C6EA)
val md_theme_dark_onTertiary = Color(0xFF23304D)
val md_theme_dark_tertiaryContainer = Color(0xFF3A4664)
val md_theme_dark_onTertiaryContainer = Color(0xFFD9E2FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1D)
val md_theme_dark_onBackground = Color(0xFFE0E3E3)
val md_theme_dark_surface = Color(0xFF191C1D)
val md_theme_dark_onSurface = Color(0xFFE0E3E3)
val md_theme_dark_surfaceVariant = Color(0xFF3F484A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC8CA)
val md_theme_dark_outline = Color(0xFF899294)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E3)
val md_theme_dark_inversePrimary = Color(0xFF006973)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4ED8E9)
val md_theme_dark_outlineVariant = Color(0xFF3F484A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF006973)

val percent1_income = Color(0xFFa3c4f3)
val percent2_income = Color(0xFF90dbf4)
val percent3_income = Color(0xFF8eecf5)
val percent4_income = Color(0xFF98f5e1)
val percent5_income = Color(0xFFb9fbc0)

val percent1_expense = Color(0xFFcfbaf0)
val percent2_expense = Color(0xFFf1c0e8)
val percent3_expense = Color(0xFFffcfd2)
val percent4_expense = Color(0xFFfde4cf)
val percent5_expense = Color(0xFFfbf8cc)